spring:
  application:
    name: spring-mongo-demo
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring-mongo-demo

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
