name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: maven build
        run: ./mvnw package

      - name: docker login
        run: docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: docker build
        run: docker build -f Dockerfile -t ghcr.io/grumpy-programmer/spring-mongo-demo:${{ github.run_id }} .

      - name: docker tag
        run: docker tag ghcr.io/grumpy-programmer/spring-mongo-demo:${{ github.run_id }} ghcr.io/grumpy-programmer/spring-mongo-demo

      - name: docker push
        run: |
          docker push ghcr.io/grumpy-programmer/spring-mongo-demo:${{ github.run_id }}
          docker push ghcr.io/grumpy-programmer/spring-mongo-demo
