name: main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: semver
        id: semver
        uses: grumpy-programmer/actions-semver-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: gradle build
        env:
          VERSION: ${{ steps.semver.outputs.version }}
        run: ./gradlew build

      - name: docker login
        run: docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: docker build
        run: docker build -f Dockerfile -t ghcr.io/grumpy-programmer/spring-mongo-demo .

      - name: docker tag
        if: ${{ steps.semver.outputs.released == 'true' }}
        env:
          VERSION: ${{ steps.semver.outputs.version }}
        run: docker tag ghcr.io/grumpy-programmer/spring-mongo-demo ghcr.io/grumpy-programmer/spring-mongo-demo:${VERSION}

      - name: docker push
        if: ${{ steps.semver.outputs.released == 'true' }}
        env:
          VERSION: ${{ steps.semver.outputs.version }}
        run: |
          docker push ghcr.io/grumpy-programmer/spring-mongo-demo:${VERSION}
          docker push ghcr.io/grumpy-programmer/spring-mongo-demo
